#!/bin/bash

# All the commands needed to update and analyze data. The only manual thing required is to place additional viscosity jobs into the ./md/jobs directory.

cd ../
cd ml/ml_m_trg/
cd scripts

python3 m_vs_tgovertstar.py
python3 johnson_model.py
python3 fit_johnson_m_fits.py

python3 md_model_fitted_m.py

python3 md_model.py
python3 fit_md.py

python3 dmax_vs_tgovertl.py
python3 dmax_vs_tgovertstar.py

cd ../../
cd ml_m_trg_50Kshift/
cd scripts

python3 m_vs_tgovertstar.py
python3 johnson_model.py
python3 fit_johnson_m_fits.py

python3 md_model.py
python3 fit_md.py

cd ../../
cd ml_m_trg_Nb2Ni3removed/
cd scripts

python3 m_vs_tgovertstar.py
python3 johnson_model.py
python3 fit_johnson_m_fits.py

python3 md_model.py
python3 fit_md.py
