#!/bin/bash

# Programs
PYTHON="python3"                        # Python version installed (3 or above)

# Directories
SCRIPTS_DIR="../scripts/"               # The directory for scripts
EXPORT_DATA="../jobs"                   # Location of run data
SAVE_DATA="../jobs_data"                # Location to save analysis data

# Files
INPUT="visc.in"                         # The LAMMPS input file
THERMO="system_nvt.txt"                 # File containing thermodynamic data
TEMP="temperature.txt"                  # The temperature of the run

# Parameters
DEGREE=5
SMOOTHING=1


# Extract data
${PYTHON} ${SCRIPTS_DIR}tg.py\
	"-d${EXPORT_DATA}"\
	"-n${THERMO}"\
	"-t${TEMP}"\
	"-k${DEGREE}"\
	"-s${SMOOTHING}"\
	"-a${SAVE_DATA}"\
